# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4bbc9c91f42c50d9fb78018877219cf1f08dfe7beb7cdae967228db7495fbffdeab7c0051907da8726fb21a15e6a51660d345bfc1d66c85be3b1a1cd85b1df

test:
  secret_key_base: ea998f2e230e106091a49dc78ff842abd4ecc22cf46d54fd1adaed5566cc65ab13e99bc09ac81da5babbd2fa049441320c7b0cb3be65549b8f955d5e3b3c9558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
